export enum UserStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  INGAME = 'INGAME',
}

export enum GameType {
  LADDER = 'LADDER',
  NORMAL_MATCHING = 'NORMAL_MATCHING',
  NORMAL_INVITE = 'NORMAL_INVITE',
  SPECIAL_MATCHING = 'SPECIAL_MATCHING',
  SPECIAL_INVITE = 'SPECIAL_INVITE',
}

export enum GameStatus {
  WAITING = 'WAITING',
  PLAYING = 'PLAYING',
  FINISHED = 'FINISHED',
}
