name: BE CI/CD

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }} # personal token

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: get time for image tag
      #   id: time
      #   run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

      - name: Build image in EC2
        id: build-image
        run: |
          docker build -t backend:latest .

      - name: Stop and remove previous container
        run: |
          docker rm -f backend:service || true

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Pull image from Amazon ECR and run container
      #   continue-on-error: true
      #   run: |
      #     cd ~/BE
      #     docker rmi be:
      #     docker-compose up -d

      - name: Pull image from Amazon ECR and run container
        run: |
          cd ~/BE
          docker image tag backend:latest backend:service
          docker-compose up -d

  # deploy:
  #   needs: build
  #   name: CD
  #   runs-on: self-hosted
  #   if: github.ref == 'refs/heads/deploy'

  #   steps:
      
